### ISSUE TITLE
Error Broken Pipe

### ISSUE THREAD

**Issue by grybnoy** [vyassu/DeepSentiment#10]
INFO:root:Loaded the Speech Recognition Module
INFO:root:Saved the input signal into WAVE File
INFO:root:Converted Speech To Text
INFO:root:Training of Model Disabled
INFO:root:Finished Loading SpeechNetSVMMulticlass Module
INFO:werkzeug:127.0.0.1 - - [03/Jun/2017 06:13:02] "POST /deepsentifile HTTP/1.1" 500 -
ERROR:werkzeug:Error on request:
Traceback (most recent call last):
  File "/home/ub/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 209, in run_wsgi
    execute(self.server.app)
  File "/home/ub/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 200, in execute
    write(data)
  File "/home/ub/.local/lib/python2.7/site-packages/werkzeug/serving.py", line 168, in write
    self.send_header(key, value)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 412, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe

I am trying it from web version. I saw problems with broken pipe, but changing timeout to 50000 does not help

**Comment by devank007** [comment]
same problem

error on uploading file  ::backend server not responding!please try after some time
