### ISSUE TITLE
SVMSentimentAnalysis_Spark throwing error help needed please..........

### ISSUE THREAD

**Issue by mskarthi96** [vyassu/DeepSentiment#18]
ubuntu:~/Documents/deepsenti/Code/Spark$ python SVMSentimentAnalysis_Spark.py
2018-03-29 12:25:19 WARN  Utils:66 - Your hostname, ubuntu resolves to a loopback address: 127.0.1.1; using 192.168.153.129 instead (on interface ens33)
2018-03-29 12:25:19 WARN  Utils:66 - Set SPARK_LOCAL_IP if you need to bind to another address
2018-03-29 12:25:20 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/usr/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file SVMSentimentAnalysis_Spark.py, line 88
DEBUG:root:Starting Text to Integer Conversion                                  
DEBUG:root:Starting Text to Integer Conversion
DEBUG:root:Starting Text to Integer Conversion
DEBUG:root:Starting Text to Integer Conversion
DEBUG:root:Max Features::0
DEBUG:root:Max Features::0
DEBUG:root:Max Features::0
DEBUG:root:Max Features::0
DEBUG:root:Balance Dataset
DEBUG:root:Balance Dataset
Traceback (most recent call last):
  File "SVMSentimentAnalysis_Spark.py", line 221, in <module>
    print main("/home/mskarthi96/Documents/deepsenti/Code/Spark/Data/005051808404.txt",True,10,"","","","")
  File "SVMSentimentAnalysis_Spark.py", line 189, in main
    model.fit(Xtrain,Ytrain)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/multiclass.py", line 277, in fit
    Y = self.label_binarizer_.fit_transform(y)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/base.py", line 455, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py", line 305, in fit
    raise ValueError('y has 0 samples: %r' % y)
ValueError: y has 0 samples: array([], dtype=float64)

how can i overcome this error

**Comment by vyassu** [comment]
the second argument has to be set to False if you want to run on the model provided in the git repo. If you set it to True, then you would have to train your own model with your own speech signals and text.

**Comment by mskarthi96** [comment]
yea that's what I'm asking when i leave it true and give the speech siganls and text input it throws me this error

**Comment by vyassu** [comment]
In that case, I would suggest you to execute Controller.py script. Follow the options and set the path of the folder containing the .WAV file and text file. Also, the first character of the .wav file is the first character of the emotion, for (e.g.) if the .WAV file contained the audio file for a happy emotion then the filename would be h_01.wav. Hope this would resolve your issue
