### ISSUE TITLE
ImportError: No module named label  

### ISSUE THREAD

**Issue by pinganzhang** [vyassu/DeepSentiment#19]
INFO:root:Loaded the Speech Recognition Module
INFO:root:Saved the input signal into WAVE File
INFO:root:Converted Speech To Text
INFO:root:Training of Model Disabled
INFO:root:Finished Loading SpeechNetSVMMulticlass Module
INFO:root:Finished Loading Test-Train data from file
Traceback (most recent call last):
  File "Controller.py", line 82, in <module>
    print main(inputpath, False) #print main("./Data/a01.wav",False)
  File "Controller.py", line 49, in main
    emotions = sp.main(filename, training,logging_level)
  File "/home/pi/DeepSentiment/Code/StandAlone/SpeechNetSVMMulticlass.py", line 176, in main
    emotionList = svmnnet.predict_emotion(data.iloc[0:1,0:2])
  File "/home/pi/DeepSentiment/Code/StandAlone/SpeechNetSVMMulticlass.py", line 100, in predict_emotion
    model = joblib.load(modelfilepath)
  File "/usr/lib/pymodules/python2.7/joblib/numpy_pickle.py", line 418, in load
    obj = unpickler.load()
  File "/usr/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1090, in load_global
    klass = self.find_class(module, name)
  File "/usr/lib/python2.7/pickle.py", line 1124, in find_class
    __import__(module)
ImportError: No module named label

what label means

**Comment by pinganzhang** [comment]
analyse (1.0.0)
argparse (1.2.1)
aubio (0.4.6)
bison (0.0.5)
blinker (1.3)
chardet (2.3.0)
colorama (0.3.2)
findspark (1.1.0)
Flask (0.10.1)
Flask-Cors (3.0.3)
gpiozero (1.4.0)
html5lib (0.999)
itsdangerous (0.24)
Jinja2 (2.7.3)
joblib (0.6.4)
lxkeymap (0.1)
MarkupSafe (0.23)
matplotlib (1.1.1rc2)
mcpi (0.1.1)
ndg-httpsclient (0.3.2)
nose (1.1.2)
numpy (1.14.2)
pandas (0.22.0)
picamera (1.13)
picraft (1.0)
pifacecommon (4.2.1)
pifacedigitalio (3.1.0)
pigpio (1.35)
Pillow (2.6.1)
pip (1.5.6)
pocketsphinx (0.1.3)
pyasn1 (0.1.7)
pygame (1.9.2a0)
pygobject (3.14.0)
pyinotify (0.9.4)
pyOpenSSL (0.13.1)
pyparsing (1.5.6)
pyserial (2.6)
python-apt (0.9.3.12)
python-dateutil (2.7.2)
pytz (2018.3)
PyYAML (3.12)
requests (2.4.3)
RPi.GPIO (0.6.3)
RTIMULib (7.2.1)
scikit-learn (0.11)
scipy (0.10.1)
sense-emu (1.0)
sense-hat (2.2.0)
setuptools (5.5.1)
simplejson (2.5.2)
six (1.8.0)
smbus (1.1)
SoundAnalyse (0.1.1)
spark (0.2.1)
SpeechRecognition (3.8.1)
spidev (3.0)
twython (3.1.2)
urllib3 (1.9.1)
Werkzeug (0.9.6)
wheel (0.24.0)
wsgiref (0.1.2)
here is the package i install

**Comment by pinganzhang** [comment]
solved the problem by installing the latest version of scipy and scikit-learn 
sudo pip install -u
