### ISSUE TITLE
Timeout value

### ISSUE THREAD

**Issue by robtow** [vyassu/DeepSentiment#4]
I changed the timeout value from 5000 to 50000 in <deepui.js>, to prevent the below error:

The output from <script.sh> is:

INFO:root:Loaded the Speech Recognition Module
INFO:root:Saved the input signal into WAVE File
INFO:root:Converted Speech To Text
INFO:root:Training of Model Disabled
INFO:root:Finished Loading SpeechNetSVMMulticlass Module
INFO:root:Finished Loading Test-Train data from file
INFO:root:Emotion Data: {'Angry': 1.0}
INFO:root:Retrieving the Training-Test Data for Speech2Text Model
INFO:root:Retrieving Validation Data for Speech2Text Model
INFO:root:Configuring the SVM Model
INFO:root: Finished Loading the saved Speech2Text Model.
INFO:root:Final Emotion set:: {'Angry': 1.0, 'data': 'that machete asians that was at how hopeless at junk'}
INFO:werkzeug:127.0.0.1 - - [30/Jan/2017 05:44:17] "POST /deepsentifile HTTP/1.1" 200 -
ERROR:werkzeug:Error on request:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 196, in execute
    write(data)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 164, in write
    self.send_header(key, value)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 401, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
IOError: [Errno 32] Broken pipe

**Comment by vyassu** [comment]
Thanks Rob for the temporary fix. I will have a look into why the webservice is taking more than 5 sec to respond to a request.
