### ISSUE TITLE
ImportError: No module named analyse

### ISSUE THREAD

**Issue by skswain96** [vyassu/DeepSentiment#6]
`./script.sh
Webservice started!! Use URL http://localhost:5000/deepsentiment
Traceback (most recent call last):
  File "./webservice.py", line 7, in <module>
    import Controller
  File "/home/sudhanshu/DeepSentiment/Code/StandAlone/Controller.py", line 1, in <module>
    import SpeechNetSVMMulticlass as sp
  File "/home/sudhanshu/DeepSentiment/Code/StandAlone/SpeechNetSVMMulticlass.py", line 4, in <module>
    import analyse as an
ImportError: No module named analyse
`

**Comment by vyassu** [comment]
Execute the command 
sudo pip install analyse
