### ISSUE TITLE
SpeechNetSVMMulticlass.py AttributeError: 'module' object has no attribute 'loudness'

### ISSUE THREAD

**Issue by piedmontlong** [vyassu/DeepSentiment#7]
After load a wav file, got the following error, any hints?

Traceback (most recent call last):
  File "Controller.py", line 82, in <module>
    print main(inputpath, False) #print main("./Data/a01.wav",False)
  File "Controller.py", line 49, in main
    emotions = sp.main(filename, training,logging_level)
  File "/Users/eflower/Documents/ai/DeepSentiment/Code/StandAlone/SpeechNetSVMMulticlass.py", line 133, in main
    data = pd.DataFrame(svmnnet.load_data(filename))                            # Invoking function to extract information from a single WAV file
  File "/Users/eflower/Documents/ai/DeepSentiment/Code/StandAlone/SpeechNetSVMMulticlass.py", line 107, in load_data
    loudness = abs(an.loudness(inputdata))
AttributeError: 'module' object has no attribute 'loudness'

**Comment by vyassu** [comment]
Please run the below command

sudo pip install analyse

**Comment by kartikbhutani7** [comment]
Getting the same error. 
@vyassu sudo pip install analyse command not able to solve the error.
Kindly help.

**Comment by kartikbhutani7** [comment]
Along with this error, on clicking upload, this message is displayed - "Backend server not responding!! Please try again after sometime"

**Comment by apul1421** [comment]
I am also getting the same error AttributeError: 'module' object has no attribute 'loudness'

**Comment by kartikbhutani7** [comment]
Mine got resolved by doing so - 
import analyse   /* don't import it as an */
And similarly, write -
loudness = abs(analyse.loudness(inputdata))

If this doesn't resolve the error, search with keyword - "analyse.py". There will be 2 files with this name at the same location. One of them is the one which is required. Second one is a different file used to find averages of list. Remove second one from this location. 
Finally, Re-run the project.

**Comment by skx300** [comment]
In the pypi, I searched 'analyse' and got the list https://pypi.python.org/pypi?%3Aaction=search&term=analyse&submit=search 

It seems like the 'analyse' without loudness is the one gives average of lists.
However, DeepSentiment requires the '**SoundAnalyse**' which has sound chunks for pitch and loudness.

But I have problem to install SoundAnalyse. I got the error:
**LINK: error LNK2001: unresolved external symbol PyInit_analyseffi**

**Comment by vyassu** [comment]
@kartikbhutani and @apul1421  : Can you please specify the operating system and python version you are using?

**Comment by RiemannInGitHub** [comment]
My solution to this problem:
if you just sudo pip install analyse, you will have the wrong analyse.py as @skx300 issued.
so you can download the SoundAnalyse, https://pypi.python.org/packages/89/45/4c6954d0b68dcd4e35524ce5fe6001f0993c96c86f0aab3716a1d63c7dc7/SoundAnalyse-0.1.1.tar.gz#md5=2f51770628d6378bdb8894e91ecce75c, and move analyse.py in this package to /Library/Python/2.7/site-packages.
Then all will be fine.
Or more directly, 
```
def loudness(chunk):
    data = numpy.array(chunk, dtype=float) / 32768.0
    ms = math.sqrt(numpy.sum(data ** 2.0) / len(data))
    if ms < 10e-8: ms = 10e-8
    return 10.0 * math.log(ms, 10.0)
```
Use this function directly. Don't forget import numpy, math.
